# Using the Clean Blog theme

title:             Models & Measurements
description:       Web site of the projet Emergences
author:            models-and-measures
email:             mula@ceremade.dauphine.fr
baseurl:           ""
url:               "https://models-and-measures.github.io/"
github_username:   models-and-measures
output :
 css: styles.css

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  
