# Using the Clean Blog theme

title:             Models & Measures Website
description:       Web site of the projet Emergences
author:            models-and-measures
email:             mula@ceremade.dauphine.fr
baseurl:           ""
url:               "https://models-and-measures.github.io/"
github_username:   models-and-measures


# Build settings
markdown:          kramdown
kramdown:
  parse_block_html: true
  parse_span_html: true
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  
